### ISSUE TITLE
Day 6 - Pay gem

### ISSUE THREAD

**Issue by excid3** [planetruby/gems#32]
The Pay gem is one I started to help simplify integrations for payment providers. https://github.com/pay-rails/pay

We've implemented Stripe, Braintree, and just merged Paddle support. It's got a simple interface for adding `subscribe` `charge` and other functionality to your billable models in Rails (ie. User, Team, Account, etc).

**Comment by geraldb** [comment]
Thanks again. Wow. Day 6 is yours.    Since you have a couple of post - let me know if you want to join the github org here so you can change / edit inline your post anytime as a committer (and I send you along an invite via github  - github orgs work via invite only - you get an email or you can visit the org here and click on the invite banner).

**Comment by excid3** [comment]
Sounds good to me 👍 Thanks for putting this together @geraldb 👍

**Comment by geraldb** [comment]
Thanks to @swanson for claiming Day 1 for the kick off and bringing in more people and helping with the updates.    PS: You should see the invite banner now on the org page. Welcome.

**Comment by swanson** [comment]
Closed by #39
