### ISSUE TITLE
Day 16 - BridgetownRB

### ISSUE THREAD

**Issue by pascalwengerter** [planetruby/gems#38]
Taking another one for a project I'm supporting / am excited about!

**Comment by geraldb** [comment]
Fantastic. Day 16 is yours. Thanks for highlighting Bridgetown.  Cheers. Prost.

**Comment by geraldb** [comment]
If am offline for today - but since you have two posts you are more than welcome to join the github org here than you can edit / change "inline" anytime as committer - github orgs work with invites (per email) or you can see the invite on the org page - let me know if interested and I send you along the invite first thing tomorrow. Cheers. Prost.

**Comment by pascalwengerter** [comment]
@geraldb lovely gesture but I'd respectfully decline the offer since there's quite a bunch of other things going on in my life at the moment - I'd prefer contributing "from the outside" rather than become responsible for an org. Cheers & gute Nacht!

Also, this issue is "solved" in #52

**Comment by geraldb** [comment]
No worries. Thanks again for the Bridgetown write-up. Cheers. Prost.
